# Generated by Django 5.2.4 on 2025-07-18 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xmldocument',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='xmldocument',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='xmldocument',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xmldocument',
            name='indexed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='xmldocument',
            name='last_modified',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='xmldocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='xmldocument',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xmldocument',
            name='filename',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
