# Generated by Django 5.2.4 on 2025-07-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_alter_xmldocument_options_xmldocument_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmldocument',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
