# Generated by Django 4.2.21 on 2025-07-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_xmldocument_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmldocument',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='xmldocument',
            name='creator',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='xmldocument',
            name='dates',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='xmldocument',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
