# Generated by Django 4.2.21 on 2025-07-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0004_xmldocument_abstract_xmldocument_creator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xmldocument',
            options={'ordering': ['-updated_at'], 'verbose_name': 'XML Document', 'verbose_name_plural': 'XML Documents'},
        ),
        migrations.AddField(
            model_name='xmldocument',
            name='subjects',
            field=models.TextField(blank=True),
        ),
    ]
