# Generated by Django 4.2.23 on 2025-08-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0005_alter_xmldocument_options_xmldocument_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmldocument',
            name='title_manually_edited',
            field=models.BooleanField(default=False),
        ),
    ]
